name: Deploy to Environment
run-name: Deploy to ${{ github.ref_name == 'main' && 'production' || 'staging' }}
on:
    push:
        branches:
          - main
        paths: 
          - 'infrastructure/**'
          - '.github/workflows/deploy-to-environment.yml'
    pull_request: 
        types: 
          - opened
          - synchronize
          - reopened
        paths:
          - 'infrastructure/**'
          - '.github/workflows/deploy-to-environment.yml'
          
concurrency: 
    group: deploy-${{ github.ref_name == 'main' && 'production' || 'staging' }}
    cancel-in-progress: true

env:
    AZ_LOCATION: ${{ vars.AZ_LOCATION || 'westeurope' }}

jobs:
    lint:
        name: Lint Bicep
        runs-on: ubuntu-24.04
        if: github.event_name == 'pull_request' 
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Lint Bicep
              run: |
                az bicep install
                az bicep build --file ./infrastructure/main.bicep 2>&1 | tee bicep_build.log
                if grep -q "warning" bicep_build.log; then
                    echo "Bicep linting found warnings."
                    exit 1
                else
                    echo "Bicep linting passed without warnings."
                fi
    
    what-if:
        name: What-If Analysis
        runs-on: ubuntu-24.04
        if: github.event_name == 'pull_request' 
        environment: production
        env:
            GH_TOKEN: ${{ github.token }}
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        steps:
            - name: Capture timestamp
              run: echo "WORKFLOW_TS=$(TZ='Europe/Copenhagen' date)" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: What-if
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    whatif=$(az deployment sub create --what-if --location ${{ env.AZ_LOCATION }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --template-file ./infrastructure/main.bicep --parameters ./infrastructure/parameters.bicepparam --what-if-result-format FullResourcePayloads)
                    echo "${whatif}"
                    {
                        echo "WHAT_IF_RESULT<<EOF"
                        echo "${whatif}"
                        echo "EOF"
                    } >> $GITHUB_ENV
            
            - name: Update PR
              run: |
                gh pr comment ${{ github.event.pull_request.number }} --body "$(cat <<EOF
                ### What-if analysis result
                \`\`\`text
                ${WHAT_IF_RESULT}
                \`\`\`
                From commit: ${{ github.event.pull_request.head.sha }}
                Started at: \`${WORKFLOW_TS}\`
                EOF
                )"

    deploy:
        name: Deployment - ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}
        runs-on: ubuntu-24.04
        environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Deploy
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                    az stack sub create --location ${{ env.AZ_LOCATION }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --template-file ./infrastructure/main.bicep --parameters ./infrastructure/parameters.bicepparam --name "cost-mgmt" --action-on-unmanage deleteAll --deny-settings-mode none --yes
